name: Review App
on:
  pull_request_target:
    types: [opened]

jobs:
  create-review-app:
    runs-on: ubuntu-latest
    steps:
      - uses: kqito/manage-heroku-review-app@bd802202dcc426578871d210d8f0106ecae70068
        with:
          action: create
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_PIPELINE_ID: ${{ secrets.HEROKU_PIPELINE_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
