name: Destroy Review App
on:
  pull_request_target:
    types: [closed]

jobs:
  destroy-review-app:
    runs-on: ubuntu-latest
    steps:
      - uses: kqito/manage-heroku-review-app@bd802202dcc426578871d210d8f0106ecae70068
        with:
          action: destroy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_PIPELINE_ID: ${{ secrets.HEROKU_PIPELINE_ID }}
